### ISSUE TITLE
Autocomplete results are returned at top of page

### ISSUE THREAD

**Issue by chrise86** [kayluhb/passkeep#3]
When using the autocomplete inputs the results are not returned relative to the input, but appear at the top of the page:

![input at top of screen](http://cl.ly/image/0G1n210V1P3m/Screen%20Shot%202013-05-10%20at%2012.48.57.png)

**Comment by kayluhb** [comment]
Fixed in the 2.0 branch. https://github.com/kayluhb/passkeep/tree/2.0

Used a different autocomplete lib.
